# Generated by Django 4.2.17 on 2025-01-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='待办事项内容')),
                ('isCompleted', models.BooleanField(default=False, verbose_name='完成状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项列表',
                'db_table': 'todo_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
